apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: social-media-ai-development

namespace: social-media-ai-dev

resources:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: development

patches:
  # Reduce replicas for development
  - target:
      kind: Deployment
      name: api-gateway
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: auth-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: content-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: ai-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: social-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: analytics-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: notification-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: web-app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

  # Reduce resource requests for development
  - target:
      kind: Deployment
      labelSelector: "app.kubernetes.io/name=social-media-ai"
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "128Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "100m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "256Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "250m"

images:
  - name: social-media-ai/api-gateway
    newTag: dev
  - name: social-media-ai/auth-service
    newTag: dev
  - name: social-media-ai/content-service
    newTag: dev
  - name: social-media-ai/ai-service
    newTag: dev
  - name: social-media-ai/social-service
    newTag: dev
  - name: social-media-ai/analytics-service
    newTag: dev
  - name: social-media-ai/notification-service
    newTag: dev
  - name: social-media-ai/web-app
    newTag: dev

configMapGenerator:
  - name: app-config
    literals:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - DEBUG=true

secretGenerator:
  - name: dev-secrets
    literals:
      - mongodb-username=admin
      - mongodb-password=devpassword123
      - redis-password=devredis123
      - jwt-secret=dev-jwt-secret-key
      - jwt-refresh-secret=dev-jwt-refresh-secret-key
