[build]
rustflags = ["-A", "unexpected_cfgs"]

# Note: These paths will be overridden by environment variables in build_android.sh
[target.aarch64-linux-android]
linker = "aarch64-linux-android30-clang"

[target.armv7-linux-androideabi]
linker = "armv7a-linux-androideabi30-clang"

[target.x86_64-linux-android]
linker = "x86_64-linux-android30-clang"

[target.i686-linux-android]
linker = "i686-linux-android30-clang" 