// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@2.10.0.

// Basic bridge functions for Miranda Core

/// Greet function for testing the bridge
Future<String> greet({required String name}) async {
  // Mock implementation for now
  return "Hello, $name! Miranda core is working.";
}

/// Add two numbers for testing the bridge
Future<int> addNumbers({required int a, required int b}) async {
  // Mock implementation for now
  return a + b;
}

/// Check if the core is initialized
Future<bool> isInitialized() async {
  // Mock implementation for now
  return true;
}